trade_config:
  amount: 1000

chart_config:
  instrument: USD_JPY
  granularity: M5
  wma_period: 20
  candle_count: 76

signal_config:
  source_column: ha_open
  signal_buy_column: ha_open
  signal_exit_column: ha_bid_open
  take_profit: 1.0
  stop_loss: 0.5