trade_config:
  amount: 1000

chart_config:
  instrument: USD_JPY
  granularity: M5
  wma_period: 20
  candle_count: 5000

signal_config:
  source_column: ha_close
  signal_buy_column: ha_high
  signal_exit_column: ha_high
  take_profit: 0.1
  stop_loss: 0.05