trade_config:
  amount: 1000

chart_config:
  instrument: USD_JPY
  granularity: M5
  wma_period: 20
  candle_count: 76

signal_config:
  source_column: ha_low
  signal_buy_column: ha_bid_high
  signal_exit_column: ha_bid_high
  take_profit: 3.0
  stop_loss: 0.0