chart_config:
  granularity: M5
  candle_count: 288
  instrument: USD_CHF

kernel_config:
  wma_period: 20

backtest_config:
  source_columns:
    - open
    - low
    - close
    - high
    - bid_open
    - bid_low
    - bid_close
    - bid_high
    - ask_open
    - ask_low
    - ask_close
    - ask_high
    - ha_open
    - ha_low
    - ha_close
    - ha_high
    - ha_bid_open
    - ha_bid_low
    - ha_bid_close
    - ha_bid_high
    - ha_ask_open
    - ha_ask_low
    - ha_ask_close
    - ha_ask_high

  take_profit:
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    - 1.0
    - 2.0
    - 3.0
    - 4.0
    - 5.0
    - 6.0
    - 7.0
    - 8.0

  stop_loss:
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 1.0
    - 2.0
    - 3.0
    - 4.0
    - 5.0

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s|%(name)s|%(levelname)s|%(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: simple
      filename: logs/mmbot-USD_CHF-backtest.log
  loggers:
    numba:
      level: WARNING
  root:
    level: DEBUG
    handlers: [console, file]