trade_config:
  amount: 1000
  bot_id: 331406a1-8ddd-415e-acd2-1474985d6fe1

chart_config:
  instrument: USD_CHF
  granularity: M5
  candle_count: 288

kernel_config:
  source_column: bid_open
  signal_buy_column: ask_close
  signal_exit_column: bid_open
  wma_period: 20
  stop_loss: 0.0
  take_profit: 0.0

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s|%(name)s|%(levelname)s|%(message)s'
    ecs:
      (): ecs_logging.StdlibFormatter
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: simple
      filename: logs/mmbot-USD_CHF-331406a1.log
    ecs_file:
      class: logging.FileHandler
      level: DEBUG
      formatter: ecs
      filename: logs/mmbot-EUR_USD-331406a1-ecs.json
  loggers:
    numba:
      level: WARNING
  root:
    level: DEBUG
    handlers: [console, file, ecs_file]