trade_config:
  amount: 1000
  bot_id: 5fbbd2b4-f47a-4d2a-bedf-c1329db8a69e

chart_config:
  instrument: AUD_CHF
  granularity: M5
  wma_period: 20
  candle_count: 288
  edge: false

signal_config:
  source_column: ha_low
  signal_buy_column: ha_open
  signal_exit_column: ha_open
  wma_period: 20
  take_profit: 1.0
  stop_loss: 0.0
  edge: false

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s|%(name)s|%(levelname)s|%(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: simple
      filename: logs/mmbot-EUR_USD-5fbbd2b4.log
  loggers:
    numba:
      level: WARNING
  root:
    level: DEBUG
    handlers: [console, file]